name: ci
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.18
          - 1.19
    name: 'ci-${{ matrix.go-version}}'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2      
      - name: Prepare cache
        uses: actions/cache@v2      
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-${{ matrix.go-version }}-
      - name: Get dependencies
        run: go get
      - name: Build
        run: go build
      - name: Test
        run: go test ./...
      - name: Lint
        run: go vet ./...
