name: release
env:
  go-version: 1.19
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  release:
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --force --tags
      - name: Prepare cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ env.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-${{ env.go-version }}-
      - name: Get dependencies
        run: go get
      - name: Build
        run: go build
      - name: Test
        run: go test ./...
      - name: Lint
        run: go vet ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
